# Generated by Django 4.0.2 on 2022-02-27 10:22

import Basic_exam.web.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_album_artist_album_name_alter_profile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_name',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2), Basic_exam.web.models.valid_only_character]),
        ),
    ]
